backend/backend/urls.py
from django.urls import path, include  # add this
from rest_framework import routers  # add this
from django.conf.urls import url, include
from django.contrib import admin


app_name = "reward"
router = routers.DefaultRouter()  # add this



urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('reward.urls')),  # add this


]


# https://www.tutorialspoint.com/django/django_url_mapping.htm

backend/reward/urls.py
from . import views
# from django.conf.urls import url
from django.conf.urls import include, url
from django.urls import path, include  # add this
from .views import searchposts, BootstrapFilterView


app_name = "reward"


urlpatterns = [

    url('^$', views.index, name="RemList"),

    path('Profile', views.profileview, name="Profile"),
    path('about', views.about_rewardview, name="About"),
    path('blind_reward', views.blind_rewardview, name="Blind Reward"),
    path('flexible_work', views.flexible_workview, name="Flexible Work"),
    # path('reward_form', RewardFormView.as_view(), name='Reward Form'),
    # url(r'^search/$', views.search, name='search'),
    # url(r'^$', searchposts, name='searchposts'),
    path('searchposts', searchposts, name="searchposts"),
    path('benefits', views.benefitsview, name="Benefits"),
    # path('reward_proposal', views.reward_proposal, name="Reward Proposal"),
    # path('reward_proposal', views.RemFilterView, name="Reward Proposal"),
    # url(r'^search/$', views.search, name='search'),
    # path('rem/<str:pk_test>/', views.reward_proposal, name="rem"),
    path('reward_form', BootstrapFilterView, name='bootstrap'),




]

backend/reward/models.py
from django.db import models


class Rem(models.Model):
    ASSETS = (
        ('NiW', 'NiW'),
        ('WAIO', 'WAIO'),
    )

    REGIONS = (
        ('MinAus', 'MinAus'),
        ('MinAm', 'MinAm'),
        ('Functions', 'Functions'),
        ('Petroleum', 'Petroleum'),
    )

    GRADES = (
        ('5', '5'),
        ('6', '6'),
        ('7', '7'),
        ('8', '8'),
        ('9', '9'),
        ('10', '10'),
        ('11', '11'),
        ('12', '12'),
        ('13', '13'),
    )

    asset_Func = models.CharField(max_length=120, null=True, blank=True, choices=ASSETS)
    grade = models.TextField(max_length=2, default="6", choices=GRADES)
    jobFamily = models.CharField(max_length=120)
    midpoint = models.IntegerField(default="100000")
    STI = models.IntegerField(default="10")
    superannuation = models.IntegerField()
    region = models.CharField(max_length=120, default="MinAus", choices=REGIONS)

    def __str__(self):
        return self.asset_Func


class Allowance(models.Model):
    name = models.CharField(max_length=120)
    annual_amount = models.IntegerField()
    asset_Func = models.ForeignKey(Rem, on_delete=models.CASCADE)
    annual_leave = models.CharField(max_length=120)
    annual_hours = models.IntegerField()

    def __str__(self):
        return self.name

backend/reward/forms.py
from django.forms import ModelForm
from .models import Rem


class RemForm(ModelForm):
    class Meta:
        model = Rem
        fields = '__all__'







# from django import forms
#
#
# Region_CHOICES = (
#     ("", "Choose..."),
#     ("1", "MinAus"),
#     ("2", "MinAmericas"),
#     ("3", "Petroleum"),
#     ("4", "GlobalFunction"),
# )
#
# AssetFunction_CHOICES = (
#     ("", "Choose..."),
#     ("1", "WAIO"),
#     ("2", "NiW"),
#     ("3", "OD"),
#     ("4", "Coal"),
# )
#
# grade_CHOICES = (
#     ("", "Choose..."),
#     ("1", "NA"),
#     ("4", "4"),
#     ("5", "5"),
#     ("6", "6"),
#     ("7", "7"),
#     ("8", "8"),
#     ("9", "9"),
#     ("10", "10"),
#     ("11", "11"),
#     ("12", "12"),
#     ("13", "13"),
# )
#
#
# jobfamily_CHOICES = (
#     ("", "Choose..."),
#     ("1", "SS01"),
#     ("2", "SS02"),
#     ("3", "SS03"),
#     ("4", "SS04"),
# )
#
# class RewardForm(forms.Form):
#     region = forms.ChoiceField(choices=Region_CHOICES)
#     Asset_Function = forms.ChoiceField(choices=AssetFunction_CHOICES)
#     grade = forms.ChoiceField(choices=grade_CHOICES)
#     job_family = forms.ChoiceField(choices=jobfamily_CHOICES)
#

backend/reward/views.py
from django.core.mail.backends import console
from django.shortcuts import render
from rest_framework import viewsets, generics  # add this
# from .serializers import RemSerializer, AllowancesSerializer  # add this
from .serializers import RemSerializer
from .models import Rem
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseBadRequest, HttpResponse, HttpResponseRedirect
from django.views.generic.list import ListView
from django.views import generic
from django.urls import reverse
from .forms import RemForm
from django.db.models import Q
import datetime


def index(request):
    return render(request, "index.html", {})


# we are passing asset_function as key and then we can render the value of the key on the html page


def profileview(request):
    # context = {
    # }
    return render(request, "profile.html", {})


# we are passing asset_function as key and then we can render the value of the key on the html page


def about_rewardview(request):
    return render(request, "about_reward.html", {})


def blind_rewardview(request):
    return render(request, "blindreward.html", {})


def flexible_workview(request):
    return render(request, "flexible_work.html", {})


def benefitsview(request):
    return render(request, "benefits.html", {})



def searchposts(request):
    if request.method == 'GET':
        query = request.GET.get('q')

        submitbutton = request.GET.get('submit')

        if query is not None:
            lookups = Q(region__icontains=query) | Q(asset_function__icontains=query)

            results = Rem.objects.filter(lookups).distinct()

            context = {'results': results,
                       'submitbutton': submitbutton}

            return render(request, 'search_page.html', context)

        else:
            return render(request, 'search_page.html')

    else:
        return render(request, 'search_page.html')


def is_valid_queryparam(param):
    return param != '' and param is not None and param !="Choose..."


def filter(request):
    qs = Rem.objects.all()
    region = request.GET.get('region')
    asset_Func = request.GET.get('asset_Func')
    grade = request.GET.get('grade')
    jobFamily = request.GET.get('jobFamily')


    if is_valid_queryparam(region):
        qs = qs.filter(region=region)

    if is_valid_queryparam(asset_Func):
        qs = qs.filter(asset_Func=asset_Func)

    if is_valid_queryparam(grade):
        qs = qs.filter(grade=grade)

    if is_valid_queryparam(jobFamily):
        qs = qs.filter(jobFamily=jobFamily)



    return qs


# def compa_ratio(proposed_Salary, midpoint):
#     proposed_Salary = int('proposed_Salary')
#     midpoint = 100000
#     # midpoint = request.GET.get('midpoint')
#     if midpoint is not None:
#
#         compa = proposed_Salary / midpoint
#     return compa


def BootstrapFilterView(request):
    qs = filter(request)
    proposed_Salary = request.GET.get('proposed_Salary')
    salary_proposed = request.GET.get('one')
    compa = salary_proposed
    STI = request.GET.get('STI')
    proposed_Date = request.GET.get('proposed_Date')

    context = {
        'queryset': qs,
        'categories': Rem.objects.all,
        'proposed_Salary': proposed_Salary,
        'salary_proposed': salary_proposed,
        'STI': STI,
        'proposed_Date': proposed_Date,

        # 'compa': compa,
        # 'compa': compa_ratio(request),
    }

    return render(request, "reward_proposal.html", context)





def date_check(request):
    proposed_Date = request.GET.get('proposed_Date')
    cutoff_Date = datetime.datetime(2020, 4, 1)
    # need to not have this hard coded!
    result = cutoff_Date - proposed_Date
    print(result)

    if proposed_Date - cutoff_Date:

        message = False

    else:
        message = True

    return message


def currency_check(request):
    region = request.GET.get('region')

    if region is "MinAus":
        currency = "AUD"

backend/reward/templates/about_reward.html
<!--<!DOCTYPE html>-->
{% extends "base_generic.html" %}

{% load static %}

<html>
{% block content %}
<head>
    <meta charset="UTF-8">
    <title>Reward App</title>
    {% load static %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css"
          integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css"
          href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/indexstyle.css' %}">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link rel="stylesheet" href="{% static 'css/profile.css' %}">
    <!--    -->
</head>
<body>
<!--    <p class="fakecrumb"> Reward>BHP Reward</p>-->
<!--    <div class="profilesummary">-->
<!--        <br>-->
<!--        <h1>BHP Reward Philosophy </h1>-->
<ul class="list-inline">
    <li class="list-inline-item">Reward</li>
    <li class="list-inline-item">BHP Reward</li>
</ul>


    <div class="profilepoints">
        <p> add notes here about median, EMV, benefits, blind reward</p>
        <h2> Useful Links</h2>
        <li class="profileli">myHR+</li>

        <li class="profileli">Need coaching?</li>
        <li class="profile1"><a href="https://spo.bhpbilliton.com/sites/HumanResources/central/Forms/Reward_101.aspx" target="_blank">BHP Reward</a></li>
  
    </div>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
</body>
</html>


{% endblock %}

backend/reward/templates/allowance.html
<html>
{% block content %}
<head>


</head>
<body>


<form name="form">

    <div class="col-md-6">
        <div class="form-row">
            <div class="form-group col-md-4">

                <input type="button" class="btn btn-info" value="Allowances" name="alw">
            </div>
            <div class="form-group col-md-3">
<!--                <label for="workschedule">Select</label><br>-->
<!--                <select id="workschedule" name="workschedule" class="form-control">-->
<!--                    <option selected>Choose...</option>-->
                    <!--                            {% for cat in categories %}-->
                    <!--                            <option value="{{ cat.region }}">{{ cat.region }}</option>-->
                    <!--                            {% endfor %}-->
<!--                </select>-->
            </div>
            {% include 'useful_links.html' %}
<!--                 <ul class="col-md-5">-->

<!--             <li><a href class="useful_link">Location specific benefits</a></li>-->
<!--            <li><a href class="useful_link">Site Information</a></li>-->
<!--            <li><a href class="useful_link">Roster information</a></li>-->
<!--        </ul>-->

        </div>
    </div>

</form>




{% endblock %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
</body>
</html>

backend/reward/templates/bonus.html
<!--<div class="col-md-6">-->

<!--    <div class="form-row">-->
<!--        &lt;!&ndash;            <div class="form-group col-md-2">&ndash;&gt;-->

<!--        &lt;!&ndash;                <input type="btn" class="btn btn-info" onClick="multiplyBy()" Value="Bonus" size="2"/>&ndash;&gt;-->
<!--        &lt;!&ndash;            </div>&ndash;&gt;-->


<!--        &lt;!&ndash;            <div class="form-group col-md-4">&ndash;&gt;-->
<!--        <label hidden for="one">Proposed Salary $</label>-->
<!--        <input hidden type="text" id="nineNumber" value="{{ proposed_Salary }}" size="3"/><br>-->
<!--        &lt;!&ndash;            </div>&ndash;&gt;-->
<!--        <div class="form-group col-md-6">-->
<!--            <label for="two">Bonus </label>-->
<!--            {% for rem in queryset %}-->
<!--            <div id="tenNumber" value=" {{ rem.STI }} " size="3"/>-->
<!--            {{ rem.STI }}%<br>-->
<!--        </div>-->

<!--        &lt;!&ndash;                  <input type="text" id="tenNumber" value=" {{ rem.STI }} " size="3"/>%<br>&ndash;&gt;-->
<!--        {% endfor %}-->
<!--    </div>-->
<!--    <div class="form-group col-md-2">-->
<!--        <div id="resultc"></div>-->

<!--    </div>-->
<!--</div>-->





<!--&lt;!&ndash;<form>&ndash;&gt;-->
<!--&lt;!&ndash;1st Number : <input type="text" id="firstNumber" /><br>&ndash;&gt;-->
<!--&lt;!&ndash;2nd Number: <input type="text" id="secondNumber" /><br>&ndash;&gt;-->
<!--&lt;!&ndash;<input type="button" onClick="multiplyBy()" Value="Multiply" />&ndash;&gt;-->

<!--&lt;!&ndash;</form>&ndash;&gt;-->
<!--&lt;!&ndash;<p>The Resulty is : <br>&ndash;&gt;-->
<!--&lt;!&ndash;<span id = "result"></span>&ndash;&gt;-->
<!--&lt;!&ndash;</p>&ndash;&gt;-->

<!--<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>-->

backend/reward/templates/divide.html
<html>

<head>

     <script language="javascript">
         document.addEventListener('DOMContentLoaded', function() {
             function multiply() {
                 var ans = (document.form.one.value) * (document.form.two.value)
                 document.form.answer.value = ans;
                 console.log(ans);
             }

         })
     </script>


</head>

<body><form name="form">
<input type="text" name="one" size="2">
<input type="text" name="two" size="2">

<input type="button" value="answer" name="now" onClick="multiply()">
<input type="text" name="answer" size="2">
</form>
</body>

</html>

backend/reward/templates/flexible_work.html
<!--<!DOCTYPE html>-->
{% extends "base_generic.html" %}

{% load static %}

<html>
{% block content %}
<head>
    <meta charset="UTF-8">
    <title>Reward App</title>
    {% load static %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css"
          integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css"
          href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/indexstyle.css' %}">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link rel="stylesheet" href="{% static 'css/profile.css' %}">
    <!--    -->
</head>
<body>
    <ul class="list-inline">
    <li class="list-inline-item">Reward</li>
    <li class="list-inline-item">Flexible Work</li>
    </ul>
<!--    <p class="fakecrumb"> Reward>Flexible Work</p>-->
    <div class="profilesummary">
        <br>
        <h1>Flexible Work at BHP </h1>

    </div>



    <div class="profilepoints">
        <p> give explanation - could add the flex work toolkits in here </p>
        <h2> Useful Links</h2>
        <li class="profileli">myHR+</li>
        <li class="profileli">Links to flex work calculators</li>
        <li class="profileli">Need coaching?</li>
    </div>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
</body>
</html>


{% endblock %}

backend/reward/templates/index.html
<!--<!DOCTYPE html>-->
{% extends "base_generic.html"  %}


 {% load static %}
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
  <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="{% static 'css/indexstyle.css' %}">
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
<html >
{% block content %}
<head>
  <meta charset="UTF-8">
  <title>Reward App</title>
  {% load static %}
<!--  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">-->
<!--  <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">-->
<!--  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">-->
<!--    -->
</head>
<body>
<!--<div django-app="Reward App">-->
<body>
    <div class="container">
            <div class="content">
                <div class="rewardform">

            <h1>Reward Form</h1>
                <br>
                <p><i>Previously known as the Reward Proposal Template</i></p>
<!--            <p class="tagline">BHP Reward</p>-->
                <p class="tagline">Did you know that at BHP we do <strong>not</strong> ask candidates for their current salary nor salary expectations?</p>
                <p class="tagline">See <a href="blind_reward" class="blind_reward_link">Blind Reward</a> for more info.</p>
<!--                {{ asset_functions  }}-->


            <form action="" method="post">
            {% csrf_token %} <!-- csrf token for basic security -->
                <div class="inputContainer">
<!--                    <input type="text" id="description" class="taskName" placeholder="Welcome, please ensure you are familiar with Blind Reward for external hires" name="description" required>-->
<!--                    <label for="description">Note</label>-->
                </div>

                <div class="inputContainer half last">
                    <i class="fa fa-caret-down selectArrow"></i>
                    <select id="region" class="taskCategory" name="category_select">
                        <option class="disabled" value="">Choose a Region</option>
                        {% for region in AssetFunction.objects.all %}
                        <option class="" value="{{ AssetFunction.region }}" name="{{ AssetFunction.region }}">{{ AssetFunction.region
                            }}
                        </option>
                        {% endfor %}
                    </select>
                    <label for="region">Region</label>
                </div>

                <div class="inputContainer half last">
                    <i class="fa fa-caret-down selectArrow"></i>
                    <select id="allowance" class="taskCategory" name="category_select">
                    <option class="disabled" value="">Choose an Asset of Function</option>
                    {% for region in asset_function %}
                        <option class="" value="{{ allowances.name }}" name="{{ allowances.name }}">{{ allowances.name }}</option>
                    {% endfor %}
                    </select>
                    <label for="Asset_Function">Asset/Function</label>
                </div>


                 <div class="inputContainer half last">
                    <i class="fa fa-caret-down selectArrow"></i>
                    <select id="allowance" class="taskCategory" name="category_select">
                    <option class="disabled" value="">Position Title</option>
                    {% for region in asset_function %}
                        <option class="" value="{{ allowances.name }}" name="{{ allowances.name }}">{{ allowances.name }}</option>
                    {% endfor %}
                    </select>
                    <label for="Position">Position</label>
                </div>

                    <div class="inputContainer half last">
                    <i class="fa fa-caret-down selectArrow"></i>
                    <select id="allowance" class="taskCategory" name="category_select">
                    <option class="disabled" value="">Graded role or TOT</option>
                    {% for region in asset_function %}
                        <option class="" value="{{ allowances.name }}" name="{{ allowances.name }}">{{ allowances.name }}</option>
                    {% endfor %}
                    </select>
                    <label for="Graded_TOT">Graded role or Trade Operator Technician role</label>
                    </div>


                    <div class="inputContainer half last">
                    <i class="fa fa-caret-down selectArrow"></i>
                    <select id="allowance" class="taskCategory" name="category_select">
                    <option class="disabled" value="">Enter Grade or na for benchmark</option>
                    {% for region in asset_function %}
                        <option class="" value="{{ allowances.name }}" name="{{ allowances.name }}">{{ allowances.name }}</option>
                    {% endfor %}
                    </select>
                    <label for="Benchmark or Grade">Enter grade or benchmark</label>
                    </div>


                    <div class="inputContainer half last">
                    <i class="fa fa-caret-down selectArrow"></i>
                    <select id="allowance" class="taskCategory" name="category_select">
                    <option class="disabled" value="">Job Family</option>
                    {% for region in asset_function %}
                        <option class="" value="{{ allowances.name }}" name="{{ allowances.name }}">{{ allowances.name }}</option>
                    {% endfor %}
                    </select>
                    <label for="Job_Family">Job Family</label>
                    </div>

                     <div class="inputContainer half last">
                    <i class="fa fa-caret-down selectArrow"></i>
                    <select id="allowance" class="taskCategory" name="category_select">
                    <option class="disabled" value="">Location</option>
                    {% for region in asset_function %}
                        <option class="" value="{{ allowances.name }}" name="{{ allowances.name }}">{{ allowances.name }}</option>
                    {% endfor %}
                    </select>
                    <label for="Location">Location</label>
                    </div>

                 <div class="inputContainer half last">
                    <i class="fa fa-caret-down selectArrow"></i>
                    <select id="allowance" class="taskCategory" name="category_select">
                    <option class="disabled" value="">Roster</option>
                    {% for region in asset_function %}
                        <option class="" value="{{ allowances.name }}" name="{{ allowances.name }}">{{ allowances.name }}</option>
                    {% endfor %}
                    </select>
                    <label for="Roster">Roster</label>
                    </div>


                <div class="inputContainer half last right">
                    <input type="date" id="dueDate" class="taskDate" name="date">
                    <label for="dueDate">Estimated start date</label>
                    <ul>
                        <li>
                            Note cutoff date for Shareplus is <strong> 1st March </strong>
                        </li>
                        <li>
                            Cutoff date for receiving this year's bonus is <strong> 1st April </strong>
                        </li>
                    </ul>

                </div>
<!--                <div class="row">-->
<!--                    <button class="taskAdd" name="taskAdd" type="submit"><i class="fa fa-plus icon"></i>Add task-->
<!--                    </button>-->
<!--                    <button class="taskDelete" name="taskDelete" formnovalidate="" type="submit"-->
<!--                            onclick="$('input#sublist').click();"><i class="fa fa-trash-o icon"></i>Delete Tasks-->
<!--                    </button>-->
<!--                </div>-->
<!--                <ul class="taskList">-->
<!--                    {% for todo in todos %} &lt;!&ndash; django template lang - for loop &ndash;&gt;-->
<!--                    <li class="taskItem">-->
<!--                        <input type="checkbox" class="taskCheckbox" name="checkedbox" id="{{ todo.id }}"-->
<!--                               value="{{ todo.id }}">-->
<!--                        <label for="{{ todo.id }}"><span class="complete-">{{ todo.title }}</span></label>-->
<!--                        <span class="category-{{ todo.category }}">{{ todo.category }}</span>-->
<!--                        <strong class="taskDate"><i class="fa fa-calendar"></i>{{ todo.created }} - {{ todo.due_date }}</strong>-->
<!--                    </li>-->
<!--                    {% endfor %}-->
<!--                </ul>-->
        <!-- taskList -->
            </form>


                </div>
            </div><!-- content -->
 </div><!-- container -->
    <br>
    <br>
    <div class="Summary">
        <div class="package">
    <table>
        <h4>Reward Summary</h4>
        <p>Package details here</p>
    </table>
<br>
    </div>

    <div class="useful">
<h4> Useful links based on your selection</h4>
    <ul>
        <li>BHP Benefits</li>
       <li>Location specific benefits</li>
        <li>Site Information</li>
        <li>Roster information; annual leave, swing, flyin and out days</li>

    </ul>


</div>
    </div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
</body>
</html>



{% endblock %}

backend/reward/templates/search_page.html
<!--<!DOCTYPE html>-->
{% extends "base_generic.html" %}

{% load static %}

<html>

<head>
    <meta charset="UTF-8">
    <title>Reward App</title>
    {% load static %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css"
          integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css"
          href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/indexstyle.css' %}">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link rel="stylesheet" href="{% static 'css/profile.css' %}">
    <!--    -->
</head>
<body>
{% block content %}
<h1>Search Results</h1>

<br/>
<form action="{% url 'reward:searchposts' %}" method="GET" value="{{request.GET.q}}">
    Search <input type="text" name="q" value="{{request.GET.q}}" placeholder="Search posts"/>
    <input type="submit" name="submit" value="Search"/>
</form>

<br>
<br>
{% if submitbutton == 'Search' and request.GET.q != '' %}
{% if results %}
<h2>Results for <b>{{ request.GET.q }}</b></h2>
<br/><br/>

{% for result in results %}

{{result.title}}
<br/>

{{result.content}}
<br/>

{% endfor %}
{% else %}
No search results for this query
{% endif %}
{% endif %}

</body>
</html>

{% endblock %}

backend/reward/templates/side_notes.html
<div class="col-md-5">
    <br>
    <h4> Did you know... </h4>
    <p class="taglineknow"> At BHP we do <strong>not</strong> ask candidates for their current
        salary nor salary expectations? <a href="blind_reward" class="blind_reward_link">Blind Reward</a></p>
    <!--            <p class="tagline">-->
    <!--            </p>-->
    <!--            <div class="col-md-12">-->
    <!--        <div class="package">-->
    <br>
    <h4>Reward Notes</h4>
    <!--                <div class="Summaryarea">-->

<p class="date" id="newdate"> Proposed start date of<strong> {{ proposed_Date }} </strong> please note the following:</p>
    <p>
        {% if mess in message is True %}
        Eligible for this year's bonus paid in September. Pro-rata due to start date.
        {% else %}
        Not eligible for this year's bonus (paid in September) <a href="" class="blind_reward_link"> More info</a>
        {% endif %}
    </p>




    <p>
        Eligible to enrol in next year's <a href="" class="blind_reward_link"> SharePlus scheme</a> (cut off
        is 1st March)

    </p>
    <!--     <p>-->
    <!--         Benefits brochure has all the details, including Novated Lease, blah-->
    <!--     </p>-->
    <p>
        Pay day is monthly/fortnightly
    </p>

</div>
<!--            </div>-->
<!--        </div>-->